easy_admin:
    site_name: 'Administration'
    formats:
        date: 'd/m/Y'
    design:
        brand-color: #42aed7;
        form_theme: 'vertical'
        menu:
            - { entity: 'User', icon: 'user', label: 'Utilisateurs' }
            - { entity: 'Observation', icon: 'binoculars', label: 'Observation' }
            - { entity: 'Bird', icon: 'themeisle', label: 'Oiseaux' }
            - { entity: 'Badge', icon: 'bookmark', label: 'Badge' }
            - label: 'Base de données'
              children:
            - { label: 'Supprimer la BDD', route: 'taxrefBaseDelete' }
            - { label: 'Importer la BDD', route: 'taxrefBaseImport' }

    entities:
        User:
            class: App\Entity\User
            list:
                title: 'Utilisateurs'
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', title: 'Editer' }
                    - { name: 'delete', icon: 'eraser', label: 'Supprimer', title: 'Supprimer' }
                    - { name: 'new', icon: 'plus-circle', label: 'Ajouter', title: 'Ajouter' }
                    - { name: 'show', icon: 'eye', label: 'Voir', title: 'Voir' }

                fields:
                    - { property: 'id' }
                    - { property: 'enabled', label: 'Actif' }
                    - { property: 'roles', label: 'Rôle' }
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'birth', label: 'Date de naissance',format: 'd/m/Y' }
                    - { property: 'email', label: 'Email', type: 'email' }
                    - { property: 'lastLogin', label: 'Dernière connexion',format: 'd/m/Y' }
                    #- { property: 'plainPassword', type: 'text', type_options: { required: false } }


            new:
                title: "Créer un nouvel utilisateur"
                fields:
                    - { type: 'tab',css_class: 'col-sm-6', label: 'Informations : Identité',icon: 'user'}
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'birth', label: ' Date de naissance', type: 'birthday' }
                    - { type: 'tab', css_class: 'col-sm-6',label: 'Informations : Compte', icon: 'user'}
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'email', label: 'Email', type: 'email' }
                   # - { property: 'enabled', label: 'Actif' }
                   # - { property: 'lastLogin', label: 'Dernière connexion',format: 'd/m/Y' }
                    - { property: 'plainPassword', type: 'text',label: 'Mot de passe', type_options: { required: true } }
                    - { type: 'tab',css_class: 'col-sm-6', label: 'Informations : Rôle ',icon: 'user'}
                    - { property: 'roles' ,type: 'choice',label: 'Rôle', type_options: { multiple: true, required: true, choices : { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN', 'ROLE_NATURALIST': 'ROLE_NATURALIST' } }}
            edit:
                title: "Edition du profil utilisateur"
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Informations : Identité', icon: 'user'}
                    - { property: 'lastname',label: 'Nom' }
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'birth', label: 'Date de naissance', type: 'birthday' }
                    - { property: 'roles', type: 'choice',label: 'Rôle', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN', 'ROLE_NATURALIST': 'ROLE_NATURALIST' } } }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Informations : Compte', icon: 'user'}
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'email', label: 'Email', type: 'email' }
                    - { property: 'enabled', label: 'Actif' }
                    - { property: 'lastLogin', label: 'Dernière connexion',format: 'd/m/Y' }
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }

            show:
                title: "Voir du profil utilisateur"
                fields:
                    - { property: 'lastname',label: 'Nom' }
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'birth', label: 'Date de naissance', format: 'd/m/Y' }
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'email', label: 'Email', type: 'email' }
                    - { property: 'enabled', label: 'Actif' }
                    - { property: 'lastLogin', label: 'Dernière connexion',format: 'd/m/Y' }
                  #  - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', label: 'Rôle' }
        Observation:
            class: App\Entity\Observation
            list:
                title: 'Observation'
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', title: 'Editer' }
                    - { name: 'delete', icon: 'eraser', label: 'Supprimer', title: 'Supprimer' }
                    - { name: 'new', icon: 'plus-circle', label: 'Ajouter', title: 'Ajouter' }
                    - { name: 'show', icon: '', label: 'Voir', title: 'Voir' }
                fields:
                    - { property: 'id'}
                    - { property: 'date', type: 'date'}
                    - { property: 'user', label: 'Utilisateur'}
                    - { property: 'statut'}
                    - { property: 'latitude'}
                    - { property: 'longitude'}
                    - { property: 'bird', label: 'Oiseau' }
                    - { property: 'description'}
            new:
                title: 'Créer une nouvelle observation'
                fields:
                    - { property: 'date', type: 'date'}
                    - { property: 'user', label: 'Utilisateur'}
                    - { property: 'statut', label: 'statut'}
                    - { property: 'latitude'}
                    - { property: 'longitude'}
                    - { property: 'bird', label: 'Oiseau' }
                    - { property: 'pictureFile',type: 'vich_image'}
                    - { property: 'description'}
            edit:
                title: "Editer l'observation"
                fields:
                    - { property: 'date', type: 'date'}
                    - { property: 'user', label: 'Utilisateur'}
                    - { property: 'statut', label: 'statut'}
                    - { property: 'latitude'}
                    - { property: 'longitude'}
                    - { property: 'bird', label: 'Oiseau'}
                    - { property: 'pictureFile',type: 'vich_image' }
                    - { property: 'description'}
            show:
                title: "voir l'observation"
                fields:
                    - { property: 'date', type: 'date'}
                    - { property: 'user', label: 'Utilisateur'}
                    - { property: 'statut', label: 'statut'}
                    - { property: 'latitude'}
                    - { property: 'longitude'}
                    - { property: 'bird', label: 'Oiseau'}
                    - { property: 'pictureFile' ,type: 'vich_image'}
                    - { property: 'description'}

        Bird:
            class: App\Entity\Bird
            list:
                title: 'Espèces'
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', title: 'Editer' }
                    - { name: 'delete', icon: 'eraser', label: 'Supprimer', title: 'Supprimer' }
                    - { name: 'new', icon: 'plus-circle', label: 'Ajouter', title: 'Ajouter' }
                    - { name: 'show', icon: '', label: 'Voir', title: 'Voir' }

                fields:

                  #  - { property: 'id'}
                    - { property: 'cdNom'}
                    - { property: 'nomVern'}
                    - { property: 'ordre'}
                    - { property: 'famille'}
                    - { property: 'lbNom'}
                    - { property: 'habitat'}
                    - { property: 'statutFR'}
            new:
                title: 'Ajouter un Oiseau'
                fields:
                    - { property: 'nomVern'}
                    - { property: 'ordre'}
                    - { property: 'famille'}
                    - { property: 'cdNom'}
                    - { property: 'lbNom'}
                    - { property: 'habitat'}
                    - { property: 'statutFR'}
            edit:
                title: "Editer l'oiseau"
                fields:
                    - { property: 'nomVern'}
                    - { property: 'ordre'}
                    - { property: 'famille'}
                    - { property: 'cdNom'}
                    - { property: 'lbNom'}
                    - { property: 'habitat'}
                    - { property: 'statutFR'}
            show:
                title: "Voir l'oiseau"
                fields:
                    - { property: 'nomVern'}
                    - { property: 'ordre'}
                    - { property: 'famille'}
                    - { property: 'cdNom'}
                    - { property: 'lbNom'}
                    - { property: 'habitat'}
                    - { property: 'statutFR'}


        Badge:
            class: App\Entity\Badge
            list:
                title: 'Badges'
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', title: 'Editer' }
                    - { name: 'delete', icon: 'eraser', label: 'Supprimer', title: 'Supprimer' }
                    - { name: 'new', icon: 'plus-circle', label: 'Ajouter', title: 'Ajouter' }
                    - { name: 'show', icon: '', label: 'Voir', title: 'Voir' }
                fields:
                    - { property: 'id'}
                    - { property: 'user', label: 'Utilisateur'}
                    - { property: 'name', label: 'Nom'}
            new:
                title: 'Créer un nouveau badge'
                fields:
                    - { property: 'user', label: 'Utilisateur'}
                    - { property: 'name', label: 'Nom'}
                    - { property: 'pictureFile', label: 'Image', type: 'vich_image'}
            edit:
                title: 'Editer un badge'
                fields:
                    - { property: 'user',label: 'Utilisateur'}
                    - { property: 'name',label: 'Nom'}
                    - { property: 'pictureFile',label: 'Image', type: 'vich_image'}












