easy_admin:
    site_name: 'Administration'
    formats:
        date: 'd/m/Y'
    design:
        brand-color: green
        menu:
            - { entity: 'User', icon: 'user', label: 'Utilisateurs' }
            - { entity: 'Observations', icon: '', label: 'Observation' }
            - { entity: 'Species', icon: '', label: 'Especes' }


    entities:
        User:
            class: App\Entity\User
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', title: 'Editer' }
                    - { name: 'delete', icon: '', label: 'Supprimer', title: 'Supprimer' }
                    - { name: 'new', icon: '', label: 'Ajouter', title: 'Ajouter' }
                fields:
                    - { property: 'id' }
                    - { property: 'lastname' }
                    - { property: 'firstname' }
                    - { property: 'birth' }
                    - { property: 'observation' }
                    - { property: 'badges' }
            new:
                title: "Créer un nouvel utilisateur"
                fields:
                    - { property: 'lastname' }
                    - { property: 'firstname' }
                    - { property: 'birth' }
                    - { property: 'observation' }
                    - { property: 'badges' }
            edit:
                title: "Edition du profil utilisateur"
                fields:
                    - { property: 'lastname' }
                    - { property: 'firstname' }
                    - { property: 'birth' }
                    - { property: 'observation' }
                    - { property: 'badges' }

        Observations:
            class: App\Entity\Observations
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', title: 'Editer' }
                    - { name: 'delete', icon: 'eraser', label: 'Supprimer', title: 'Supprimer' }
                    - { name: 'new', icon: 'plus-circle', label: 'Ajouter', title: 'Ajouter' }
                    - { name: 'show', icon: '', label: 'Voir', title: 'Voir' }
                fields:
                    - { property: 'id'}
                    - { property: 'date'}
                    - { property: 'latitude'}
                    - { property: 'longitude'}
                    - { property: 'picture', label: 'Image'}
                    - { property: 'bird', label: 'Oiseau'}
                    - { property: 'user', label: 'Utilisateur'}
                    - { property: 'statut'}
                    - { property: 'description'}
            new:
                title: 'Créer une nouvelle observation'
                fields:
                    - { property: 'date', type: 'date'}
                    - { property: 'latitude'}
                    - { property: 'longitude'}
                    - { property: 'picture', label: 'Image'}
                    - { property: 'bird', label: 'Oiseau'}
                    - { property: 'user', label: 'Utilisateur'}
                    - { property: 'statut'}
                    - { property: 'description'}
            edit:
                title: "Editer l'observation"
                fields:
                    - { property: 'date', type: 'date'}
                    - { property: 'latitude'}
                    - { property: 'longitude'}
                    - { property: 'picture', label: 'Image'}
                    - { property: 'bird', label: 'Oiseau'}
                    - { property: 'user', label: 'Utilisateur'}
                    - { property: 'statut'}
                    - { property: 'description'}
            show:
                title: "Voir l'observation"
                fields:
                    - { property: 'date', type: 'date'}
                    - { property: 'latitude'}
                    - { property: 'longitude'}
                    - { property: 'picture', label: 'Image'}
                    - { property: 'bird', label: 'Oiseau'}
                    - { property: 'user', label: 'Utilisateur'}
                    - { property: 'statut'}
                    - { property: 'description'}

        Species:
            class: App\Entity\Species
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', title: 'Editer' }
                    - { name: 'delete', icon: 'eraser', label: 'Supprimer', title: 'Supprimer' }
                    - { name: 'new', icon: 'plus-circle', label: 'Ajouter', title: 'Ajouter' }
                    - { name: 'show', icon: '', label: 'Voir', title: 'Voir' }
                fields:
                    - { property: 'order'}
                    - { property: 'family'}
                    - { property: 'cdNom'}
                    - { property: 'lbNom'}
                    - { property: 'nomVern'}
                    - { property: 'habitat'}
                    - { property: 'statut'}
                    - { property: 'url'}
            new:
                title: 'Créer un nouvel oiseau'
                fields:
                    - { property: 'order'}
                    - { property: 'family'}
                    - { property: 'cdNom'}
                    - { property: 'lbNom'}
                    - { property: 'nomVern'}
                    - { property: 'habitat'}
                    - { property: 'statut'}
                    - { property: 'url'}
            edit:
                title: "Editer l'oiseau"
                fields:
                    - { property: 'order'}
                    - { property: 'family'}
                    - { property: 'cdNom'}
                    - { property: 'lbNom'}
                    - { property: 'nomVern'}
                    - { property: 'habitat'}
                    - { property: 'statut'}
                    - { property: 'url'}
            show:
                title: "Voir l'oiseau"
                fields:
                    - { property: 'order'}
                    - { property: 'family'}
                    - { property: 'cdNom'}
                    - { property: 'lbNom'}
                    - { property: 'nomVern'}
                    - { property: 'habitat'}
                    - { property: 'statut'}
                    - { property: 'url'}









