easy_admin:
    site_name: 'Administration'
    formats:
        date: 'd/m/Y'
    design:
        brand-color: green
        form_theme: 'vertical'
        menu:
            - { entity: 'User', icon: 'user', label: 'Utilisateurs' }
<<<<<<< HEAD
            - { entity: 'Observation', icon: 'binoculars', label: 'Observation' }
            - { entity: 'Species', icon: 'themeisle', label: 'Especes' }
            - { entity: 'Badge', icon: 'bookmark', label: 'Badge' }

=======
            - { entity: 'Observations', icon: 'binoculars', label: 'Observations' }
            - { entity: 'Species', icon: 'themeisle', label: 'Especes' }
            - { entity: 'Badge', icon: 'bookmark', label: 'Badge' }


>>>>>>> 6e56c423c88086b41d509e95afb68723547553a4
    entities:
        User:
            class: App\Entity\User
            list:
                title: 'Utilisateurs'
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', title: 'Editer' }
                    - { name: 'delete', icon: 'eraser', label: 'Supprimer', title: 'Supprimer' }
                    - { name: 'new', icon: 'plus-circle', label: 'Ajouter', title: 'Ajouter' }
<<<<<<< HEAD
                   # - { name: 'show', icon: 'eye', label: 'Voir', title: 'Voir' }
=======
                    - { name: 'show', icon: 'eye', label: 'Voir', title: 'Voir' }
>>>>>>> 6e56c423c88086b41d509e95afb68723547553a4
                fields:
                    - { property: 'id' }
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'birth', label: 'Date de naissance',type: 'date' }
<<<<<<< HEAD
                    - { property: 'observations' }
=======
                    - { property: 'observation' }
>>>>>>> 6e56c423c88086b41d509e95afb68723547553a4
                    - { property: 'badges' }
            new:
                title: "Créer un nouvel utilisateur"
                fields:
                    - { type: 'group',css_class: 'col-sm-6', label: 'Informations : compte',icon: 'user'}
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'birth', label: ' Date de naissance', type: 'date' }
                    - { type: 'group', css_class: 'col-sm-6',label: 'Informations : détails', icon: 'plus-circle'}
<<<<<<< HEAD
                    - { property: 'observations' }
=======
                    - { property: 'observation' }
>>>>>>> 6e56c423c88086b41d509e95afb68723547553a4
                    - { property: 'badges' }
            edit:
                title: "Edition du profil utilisateur"
                fields:
                    - { type: 'tab', css_class: 'col-sm-6', label: 'Informations : compte', icon: 'user'}
                    - { property: 'lastname',label: 'Nom' }
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'birth', label: 'Date de naissance', type: 'date' }
                    - { type: 'tab', css_class: 'col-sm-6', label: 'Informations : détails', icon: 'plus-circle'}
<<<<<<< HEAD
                    - { property: 'observations' }
                    - { property: 'badges' }

        Observation:
            class: App\Entity\Observation
            list:
                title: 'Observation'
=======
                    - { property: 'observation' }
                    - { property: 'badges' }

        Observations:
            class: App\Entity\Observations
            list:
                title: 'Observations'
>>>>>>> 6e56c423c88086b41d509e95afb68723547553a4
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', title: 'Editer' }
                    - { name: 'delete', icon: 'eraser', label: 'Supprimer', title: 'Supprimer' }
                    - { name: 'new', icon: 'plus-circle', label: 'Ajouter', title: 'Ajouter' }
<<<<<<< HEAD
                  #  - { name: 'show', icon: '', label: 'Voir', title: 'Voir' }
=======
                    - { name: 'show', icon: '', label: 'Voir', title: 'Voir' }
>>>>>>> 6e56c423c88086b41d509e95afb68723547553a4
                fields:
                    - { property: 'id'}
                    - { property: 'date', type: 'date'}
                    - { property: 'user', label: 'Utilisateur'}
                    - { property: 'statut'}
                    - { property: 'latitude'}
                    - { property: 'longitude'}
                    - { property: 'bird', label: 'Oiseau' }
                    - { property: 'description'}
                   # - { property: 'pictureFile', label: 'Image', type: 'vich_picture'}
            new:
                title: 'Créer une nouvelle observation'
                fields:
                    - { property: 'date', type: 'date'}
                    - { property: 'user', label: 'Utilisateur'}
<<<<<<< HEAD
                    - { property: 'statut', label: 'statut'}
=======
                    - { property: 'statut', label: 'statut', type: 'choice', type_options: { expanded: true, multiple: false, choices: {'Non traitée' : 'untreated', 'Acceptée' : 'accepted', 'Rejetée' : 'rejected', 'Brouillon' : 'draft' }, choice_attr: {'style' : 'width: 100px'}}}
>>>>>>> 6e56c423c88086b41d509e95afb68723547553a4
                    - { property: 'latitude'}
                    - { property: 'longitude'}
                    - { property: 'bird', label: 'Oiseau'}
                    - { property: 'pictureFile',type: 'vich_image'}
                    - { property: 'description'}
            edit:
                title: "Editer l'observation"
                fields:
                    - { property: 'date', type: 'date'}
                    - { property: 'user', label: 'Utilisateur'}
<<<<<<< HEAD
                    - { property: 'statut', label: 'statut'}
=======
                    - { property: 'statut', label: 'statut', type: 'choice', type_options: { expanded: true, multiple: false, choices: {'Non traitée' : 'untreated', 'Acceptée' : 'accepted', 'Rejetée' : 'rejected', 'Brouillon' : 'draft' }, choice_attr: {'style' : 'width: 100px'}}}
>>>>>>> 6e56c423c88086b41d509e95afb68723547553a4
                    - { property: 'latitude'}
                    - { property: 'longitude'}
                    - { property: 'bird', label: 'Oiseau'}
                    - { property: 'pictureFile' ,type: 'vich_image'}
                    - { property: 'description'}
<<<<<<< HEAD
=======
          #  show:
          #      title: "Voir l'observation"
          #      fields:
          #          - { property: 'date', type: 'date'}
          #          - { property: 'user', label: 'Utilisateur'}
          #          - { property: 'statut'}
          #          - { property: 'latitude'}
          #          - { property: 'longitude'}
          #          - { property: 'bird', label: 'Oiseau'}
          #          - { property: 'pictureFile', type: 'vich_image'}
          #          - { property: 'description'}
>>>>>>> 6e56c423c88086b41d509e95afb68723547553a4

        Species:
            class: App\Entity\Species
            list:
                title: 'Espèces'
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', title: 'Editer' }
                    - { name: 'delete', icon: 'eraser', label: 'Supprimer', title: 'Supprimer' }
                    - { name: 'new', icon: 'plus-circle', label: 'Ajouter', title: 'Ajouter' }
<<<<<<< HEAD
                  #  - { name: 'show', icon: '', label: 'Voir', title: 'Voir' }
=======
                    - { name: 'show', icon: '', label: 'Voir', title: 'Voir' }
>>>>>>> 6e56c423c88086b41d509e95afb68723547553a4
                fields:
                    - { property: 'id'}
                    - { property: 'ordre'}
                    - { property: 'famille'}
                    - { property: 'cdNom'}
                    - { property: 'lbNom'}
                    - { property: 'nomVern'}
                    - { property: 'habitat'}
                    - { property: 'statut'}
                    - { property: 'url'}
            new:
                title: 'Ajouter un Oiseau'
                fields:
                    - { property: 'ordre'}
                    - { property: 'famille'}
                    - { property: 'cdNom'}
                    - { property: 'lbNom'}
                    - { property: 'nomVern'}
                    - { property: 'habitat'}
                    - { property: 'statut'}
                    - { property: 'url'}
            edit:
                title: "Editer l'oiseau"
                fields:
                    - { property: 'ordre'}
                    - { property: 'famille'}
                    - { property: 'cdNom'}
                    - { property: 'lbNom'}
                    - { property: 'nomVern'}
                    - { property: 'habitat'}
                    - { property: 'statut'}
                    - { property: 'url'}
<<<<<<< HEAD
=======
           # show:
           #     title: "Voir l'oiseau"
            #    fields:
            #        - { property: 'ordre'}
            #        - { property: 'famille'}
            #        - { property: 'cdNom'}
            #        - { property: 'lbNom'}
            #        - { property: 'nomVern'}
           #         - { property: 'habitat'}
            #        - { property: 'statut'}
            #        - { property: 'url'}
>>>>>>> 6e56c423c88086b41d509e95afb68723547553a4

        Badge:
            class: App\Entity\Badge
            list:
                title: 'Badges'
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', title: 'Editer' }
                    - { name: 'delete', icon: 'eraser', label: 'Supprimer', title: 'Supprimer' }
                    - { name: 'new', icon: 'plus-circle', label: 'Ajouter', title: 'Ajouter' }
                    #- { name: 'show', icon: '', label: 'Voir', title: 'Voir' }
                fields:
                    - { property: 'id'}
                    - { property: 'user', label: 'Utilisateur'}
<<<<<<< HEAD
                    - { property: 'name', label: 'Nom'}
=======
>>>>>>> 6e56c423c88086b41d509e95afb68723547553a4
                   # - { property: 'pictureFile', type: 'vich_image'}
            new:
                title: 'Créer un nouveau badge'
                fields:
                    - { property: 'user', label: 'Utilisateur'}
<<<<<<< HEAD
                    - { property: 'name', label: 'Nom'}
=======
>>>>>>> 6e56c423c88086b41d509e95afb68723547553a4
                    - { property: 'pictureFile', label: 'Image', type: 'vich_image'}
            edit:
                title: 'Editer un badge'
                fields:
                    - { property: 'user',label: 'Utilisateur'}
<<<<<<< HEAD
                    - { property: 'name',label: 'Nom'}
                    - { property: 'pictureFile',label: 'Image', type: 'vich_image'}

=======
                    - { property: 'pictureFile',label: 'Image', type: 'vich_image'}
           # show:
            #    title: 'Voir un badge'
            #    fields:
            #        - { property: 'user',label: 'Utilisateur'}
            #        - { property: 'picture', label: 'Image',type: 'image'}
>>>>>>> 6e56c423c88086b41d509e95afb68723547553a4













