security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt
    providers:
        in_memory: { memory: ~ }
        fos_userbundle:
                    id: fos_user.user_provider.username_email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                    provider: fos_userbundle
                    login_path: /connexion
                    check_path: /connexion_check
                    default_target_path: /interface/
                    always_use_default_target_path: true
                    #csrf_provider: form.csrf_provider
            anonymous: true
            logout:
                path: /deconnexion
                target: /connexion

    access_control:
         - { path: ^/connexion$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/manage, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/interface/*, roles: ROLE_USER }
         - { path: ^/admin/*, roles: ROLE_ADMIN }

    role_hierarchy:
            ROLE_NATURALIST:  ROLE_USER
            ROLE_ADMIN:       [ROLE_NATURALIST, ROLE_ADMIN]

fos_user:
        db_driver: orm
        firewall_name: main
        user_class: App\Entity\User
        from_email:
                address:        noreply@nao.com
                sender_name:    Nos Amis les Oiseaux
        registration:
                confirmation:
                        enabled: true
                        template: FOSUserBundle:Registration:email.txt.twig
        resetting:
                email:
                    template: FOSUserBundle:Resetting:email.txt.twig
