parameters:
    app.path.observations: /uploads/observations
    app.path.avatar: /uploads/avatar
vich_uploader:
    db_driver: orm

    mappings:
        observations_images:
            uri_prefix: '%app.path.observations%'
            upload_destination: '%kernel.project_dir%/public/uploads/observations'
            namer: vich_uploader.namer_uniqid
            delete_on_update: true
            delete_on_remove: true

        avatar_images:
            uri_prefix: '%app.path.avatar%'
            upload_destination: '%kernel.project_dir%/public/uploads/avatar'
            namer: vich_uploader.namer_uniqid
            delete_on_update: true
            delete_on_remove: true
