parameters:
    app.path.images: ../public/assets/img
vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix: '%app.path.images%'
            upload_destination: '%kernel.project_dir%/public/assets/img'
            namer: vich_uploader.namer_uniqid
            delete_on_update: true
            delete_on_remove: true
